services:

  bot:
    image: node:lts-slim
    init: true
    restart: on-failure
    command: '/bin/sh -c "while true; do sleep 10; done"'
    ports:
    - 9876:9876
    volumes:
    -  .:/app
    -  node_modules:/app/node_modules

volumes:
  node_modules:
